language: cpp
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      env: CASADI_PREFIX="${HOME}/casadi"
      install: ci/install-osx.sh

    # - os: linux
    #   dist: trusty
    #   compiler: gcc
    #   install: ci/install-linux.sh

script:
  - ci/build.sh
  - ci/test.sh
