#------------- EKF parameters ----------------
#
# Defines parameters used by the Extended Kalman Filter:
# - Sensor bias
# - Covariance matrices
#
# ----------------------------------------------------

## general settings for the EKF
is_simulation: false # 1=runs in simulation (SIL), 0=runs on drone
use_gps: true #!!only read if is_simulation=0!!:0=use optitrack, 1=use px4 gps
use_magnetometer: true #!!only read if is_simulation=0!!:0=do not use px4 magnetometer, 1=use px4 magnetometer
use_barometer: true #!!only read if is_simulation=0!!:0=do not use px4 barometer, 1=use px4 barometer
use_torque: false #0=do not use torque from vehicle model, 1=use torque from vehicle model
predict_on_idle: true #!!only read if is_simulation=0!!:1:navigation runs on idle state, 0:navigation does not run on idle state

imu_calibration_number_of_samples: 2000 #!!only used if is_simulation=0!!:1: number of samples needed to calibrate imu


## Sensor bias

gyro_bias_x: 0.0 # [rad.s^-1]
gyro_bias_y: 0.0 # [rad.s^-1]
gyro_bias_z: 0.0 # [rad.s^-1]

acc_bias_x: 0.0 # [m.s^-2]
acc_bias_y: 0.0 # [m.s^-2]
acc_bias_z: 0.0 # [m.s^-2]

mag_bias_x: 0.0 # [T]
mag_bias_y: 0.0 # [T]
mag_bias_z: 0.0 # [T]

mag_declination: 0 #[rad] #magnetic declination at launch

# magnetometer calibration matrices: A and B such that: m_calibrated = A*(m_uncalibrated - b)
A_mag_00: 1.3425
A_mag_01: 0.3672
A_mag_02: -0.0384
A_mag_10: 0.3672
A_mag_11: 1.0343
A_mag_12: 0.0327
A_mag_20: -0.0384
A_mag_21: 0.0327
A_mag_22: 0.8007

b_mag_0: 0.000003097
b_mag_1: -0.000000303
b_mag_2: -0.000003619

### covariance matrices

## prediction / process covariance (Q) matrix
## ONLY THE DIAGONAL
Q_pos_x: 0.5 # pos x noise [m^2]
Q_pos_y: 0.5 # pos y noise [m^2]
Q_pos_z: 0.5 # pos z noise [m^2]
Q_vel_x: 0.5 # vel x noise [m^2.s^-2]
Q_vel_y: 0.5 # vel y noise [m^2.s^-2]
Q_vel_z: 0.5 # vel z noise [m^2.s^-2]
Q_wq: 0.000005 # qw noise
Q_wx: 0.000005 # qx noise
Q_wy: 0.00000005 # qy noise
Q_wz: 0.00000005 # qz noise
Q_om_x: 0.00002182 # omega x noise [rad^2.s^-2]
Q_om_y: 0.00002528 # omega y noise [rad^2.s^-2]
Q_om_z: 0.00000384 # omega z noise [rad^2.s^-2]
Q_dist_force_x: 0.00001  # disturbance force x noise [N^2]
Q_dist_force_y: 0.00001  # disturbance force y noise [N^2]
Q_dist_force_z: 0.00001  # disturbance force z noise [N^2]
Q_dist_torque_x: 0.00001  # disturbance torque x noise  [N^2.m^2]
Q_dist_torque_y: 0.00001  # disturbance torque y noise  [N^2.m^2]
Q_dist_torque_z: 0.00001  # disturbance torque z noise [N^2.m^2]

## measurement update covariances (R) / sensor covarience matrix
## ONLY THE DIAGONAL

R_gyro_x: 0.00002182 #gyroscope covariance [rad^2.s^-2]
R_gyro_y: 0.00002528  #gyroscope covariance [rad^2.s^-2]
R_gyro_z: 0.00000384 #gyroscope covariance [rad^2.s^-2]

R_acc_x: 0.0053 #accelerometer covariance [m^2.s^-4]
R_acc_y: 0.0072 #accelerometer covariance [m^2.s^-4]
R_acc_z: 0.0052 #accelerometer covariance [m^2.s^-4]

R_mag_x: 0.000000000000131 #magnetometer covariance [T^2]
R_mag_y: 0.000000000000178 #magnetometer covariance [T^2]
R_mag_z: 0.000000000001149 #magnetometer covariance [T^2]

R_baro: 0.0579 #barometer covariance [m^2]

R_gps_x: 0.64 #gps covariance [m^2] # we get this information from the gps system when not in simulation
R_gps_y: 0.64 #gps covariance [m^2] # we get this information from the gps system when not in simulation

R_optitrack_x: 0.000000001 #optitrack covariance [m^2]
R_optitrack_y: 0.000000001 #optitrack covariance [m^2]
R_optitrack_z: 0.000000001 #optitrack covariance [m^2]

R_fsen_x: 10 #fake sensor "covariance" [m^2.s^-2]
R_fsen_y: 10 #fake sensor "covariance" [m^2.s^-2]
R_fsen_z: 10 #fake sensor "covariance" [m^2.s^-2]

## fake gps parameters
fake_gps_freq: 10
fake_gps_variance_xy: 0.8



