#------------- Rocket parameters --------------------
#
# Defines parameters specific to the rocket:
#   - General dimensions of the components
#   - Rocket engine specifications
#
# ----------------------------------------------------
stages: 4
diameters:
  - 0
  - 0.156 
  - 0.156 
  - 0.135
stage_z:
  - 0 
  - 0.242 
  - 3.43 
  - 3.51 
fin_n: 4
fin_top_offset: 3.15 
fin_span: 0.17
fin_root_chord: 0.28 # base length
fin_tip_chord: 0.125
fin_sweep: 0.107
fin_thickness: 0.004
lug_n: 2
lug_S: 5.7e-4 
dry_mass: 34.027 #34.027 # Dry rocket mass + ABS leftover : 32.947 + (2.2-1.12)

dry_CM: 1.77
dry_I:
  - 39
  - 39
  - 2
propellant_mass: 7.37 #4.65
propellant_CM: 2.5
Isp: 178
maxThrust:
  - 100
  - 100
  - 3000
minThrust: 
  - -100
  - -100
  - 0
minTorque: -50
maxTorque: 50
Cd:
  - 2
  - 2
  - 0.3
throttling: True
input_delay: 34.0e-3 # Mean delay between external actions and its reception
output_delay: 80.0e-3 # Mean delay between output command and its effect